name: Linphone Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (required for Linphone build)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      ## Set up Gradle version 7.4 (or any version you need)
      - name: Set up Gradle 7.4
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.4'  # specify your desired Gradle version here

      # Grant execute permissions for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Install required dependencies, using Qt5 instead of Qt6
      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libv4l-dev \
            libglew-dev \
            qt5-qmake \
            qtbase5-dev \
            qtchooser \
            libxkbcommon-x11-0

      # Build the debug APK
      - name: Build Linphone Debug APK
        run: ./gradlew wrapper --gradle-version 7.4

      - name: List files in output directory
        run: ls -R app/build/outputs/apk/

      # Upload the built APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: linphone-debug-apk
          path: app/build/outputs/apk/debug/*.apk
