name: Linphone Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java 11 (required for Linphone build)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # Download and install Gradle 7.x if not included in the project
      - name: Set up Gradle 7.4
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.4'  # Replace with specific 7.x version if needed

      # Grant execute permissions for Gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Install dependencies that Linphone might require
      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libv4l-dev libglew-dev qt6-base-dev qt6-svg-dev libxkbcommon-x11-0

      # Build the debug APK
      - name: Build Linphone Debug APK
        run: ./gradlew assembleDebug

      # Upload the built APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: linphone-debug-apk
          path: app/build/outputs/apk/debug/*.apk
